version: '3.8'
services:
  sijahub-web:
    image: nginx:alpine
    container_name: sijahub-frontend
    ports:
      - "8443:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sijahub-backend

  sijahub-backend:
    build: ./sija_connect
    container_name: sijahub-api
    restart: always
    environment:
      - MONGO_URI=mongodb+srv://violashafa:viola123@cluster0.lyvx0c2.mongodb.net/sijahub_db?retryWrites=true&w=majority
      - PORT=5000