server {
    listen 80;

    # Folder utama adalah /usr/share/nginx/html
    root /usr/share/nginx/html;

    location / {
        # Jika orang buka root, arahkan ke pages/index.html
        index pages/index.html;
        try_files $uri $uri/ /pages/index.html;
    }

    # Tambahkan ini supaya Nginx bisa baca folder lainnya
    location /css/ { }
    location /js/ { }
    location /assets/ { }
    location /components/ { }

    # Bagian API Backend tetap sama
    location /api/ {
        proxy_pass http://sijahub-api:5000/;
    }
}