server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location / {
        # Mencari file di dalam folder pages
        root /usr/share/nginx/html/pages;
        index index.html index.htm;
        
        # Jika Viola buka /daftar_siswa.html, Nginx cari di folder pages
        try_files $uri $uri/ /index.html;
    }

    # Biar folder CSS, JS, Assets tetap bisa diakses dari root
    location /css/ { root /usr/share/nginx/html; }
    location /js/ { root /usr/share/nginx/html; }
    location /assets/ { root /usr/share/nginx/html; }
    location /components/ { root /usr/share/nginx/html; }

    # Koneksi ke API Backend
    location /api/ {
        proxy_pass http://sijahub-api:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}