server {
    listen 80;
    
    location / {
        # Tambahkan /pages di ujungnya
        root /usr/share/nginx/html/pages; 
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Tambahkan ini agar CSS/JS dari folder lain tetap terbaca
    location /css/ {
        root /usr/share/nginx/html;
    }
    
    location /assets/ {
        root /usr/share/nginx/html;
    }

    location /api/ {
        proxy_pass http://sijahub-api:5000/;
    }
}